site_name: Drobnoustrój

theme:
  name: material
  language: pl

nav:
  - Co tutaj się dzieje?: index.md
  - Cybernetyka polityczna:
      - Ramy debaty: ramy-debaty.md

markdown_extensions:
  - admonition
  - pymdownx.details